### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by EvansPM** [BuysDB/plotting3dprinter#1]
After removing `-o` option because of  `svgto3dprintplot: error: unrecognized arguments: -o`.
i got:
```    
start = parse_coord(inp)
  File "c:\python38\lib\site-packages\plotting3dprinter\svg_interpreter.py", line 27, in parse_coord
    return np.array([ float(next(inp)),  float(next(inp))])
ValueError: could not convert string to float: '171.862799C153.230394'
```

Python 3
Windows

**Comment by BuysDB** [comment]
Thanks. I think I did fix this, just not uploaded. I'll update the documentation and code soon.

**Comment by BuysDB** [comment]
I've pushed the changes, could you re-try with one of the example SVGs?

**Comment by EvansPM** [comment]
Ok got some code, thanks for your fast answer.
Work well with your svg example.
Now i have to figure out why my svg created with Potrace do not work.

**Comment by BuysDB** [comment]
You have to remove the groups and make the paths absolute as (now) written in the readme

**Comment by EvansPM** [comment]
Ok Thanks

**Comment by EvansPM** [comment]
Hello,
i read what you said to obtain your SVG file.
It's where i have issue, can please explain me how you managed to get lines instead of round think?
I'm looking for to get line for my "hello Word". I use potrace to get svg. I event test with your example image but...
I know event if a line is round up i will get the final result look same like original image but it's westing time to round a line if we can just trace a line at once.
![Cercle](https://user-images.githubusercontent.com/51214539/122400197-bb27d480-cf38-11eb-95a5-a0750e97b226.png)

**Comment by BuysDB** [comment]
That is caused by potrace rather than this library. Potrace just generates contours, not central lines. What helps to do is first binarize the image and then use a binary erosion to make the lines of the input bitmap image thinner. Then the lines in the resulting potrace output will almost overlap giving a quite nice result.

**Comment by EvansPM** [comment]
Thank you to pointing me to the rigth direction, i'm looking rigth now the binary erosion with OpenCV. Look like will take a lot of work before to come to single line...
